info:
  name: Get Product Inventory
  type: http
  seq: 2

http:
  method: get
  url: "{{baseUrl}}/inventory/1"
  headers:
    - name: Authorization
      value: Bearer {{token}}
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
