spring.application.name=order-service
spring.profiles.default=${SPRING_PROFILES_DEFAULT:local}
server.port=${SERVER_PORT:8080}
product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=order-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.utsav.order_service.event

spring.kafka.consumer.properties.spring.json.use.type.headers=false

resilience4j.circuitbreaker.instances.productClient.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.productClient.slidingWindowSize=100
resilience4j.circuitbreaker.instances.productClient.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.productClient.failureRateThreshold=50
resilience4j.circuitbreaker.instances.productClient.waitDurationInOpenState=30s

resilience4j.retry.instances.productClient.maxAttempts=3
resilience4j.retry.instances.productClient.waitDuration=500ms
resilience4j.retry.instances.productClient.enableExponentialBackoff=true
resilience4j.retry.instances.productClient.exponentialBackoffMultiplier=2
resilience4j.retry.instances.productClient.retryExceptions[0]=org.springframework.web.client.ResourceAccessException
resilience4j.retry.instances.productClient.retryExceptions[1]=org.springframework.web.client.HttpServerErrorException
resilience4j.retry.instances.productClient.ignoreExceptions[0]=com.utsav.order_service.exception.ProductNotFoundException

resilience4j.bulkhead.instances.productClient.maxConcurrentCalls=10
