spring.application.name=product_service
spring.profiles.default=${SPRING_PROFILES_DEFAULT:local}
server.port=${SERVER_PORT:8083}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/product_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
