info:
  name: Get Product Inventory
  type: http
  seq: 2

http:
  method: get
  url: http://localhost:8081/inventory/1
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
