info:
  name: Reserve Inventory
  type: http
  seq: 5

http:
  method: post
  url: http://localhost:8081/inventory/102/reserve
  headers:
    - name: Content-Type
      value: application/json
  body:
    type: json
    data: |-
      {
        "quantity": 2
      }
  auth: inherit

settings:
  encodeUrl: false
  timeout: 0
  followRedirects: true
  maxRedirects: 5
